# swiftmailer:
#     url: '%env(MAILER_URL)%'
#     spool: { type: 'memory' }
swiftmailer:
    transport:  gmail
    encryption: ssl
    auth_mode:  login
    host:       smtp.gmail.com
    username:   hlotfi.hamza.lotfi@gmail.com
    password:   Lotfi1997.#
    port: 465