# swiftmailer:
#     url: '%env(MAILER_URL)%'
#     spool: { type: 'memory' }
swiftmailer:
    transport:  gmail
    encryption: ssl
    auth_mode:  login
    host:       smtp.gmail.com
    username:   email
    password:   password
    port: 465